### ISSUE TITLE
import { SortableTreeWithoutDndContext as SortableTree } from 'react-sortable-tree';

### ISSUE THREAD

**Issue by orgpark** [fritz-c/react-sortable-tree#222] opened 2018-01-03 02:36 UTC
When I have following line in my meteor app:
```
import { SortableTreeWithoutDndContext as SortableTree } from 'react-sortable-tree';
```

I get this error:
```
  "!!../css-loader/index.js??ref--2-1!../postcss-loader/lib/index.js??ref--2-2!./styles.css" in /Users/orgpark/workspace/short-lnk/node_modules/react-sortable-tree/dist/main.js (web.browser)
  "!!../node_modules/css-loader/index.js??ref--1-1!../node_modules/postcss-loader/lib/index.js??ref--1-2!../node_modules/sass-loader/lib/loader.js!./tree-node.scss" in
/Users/orgpark/workspace/short-lnk/node_modules/react-sortable-tree/dist/main.js (web.browser)
  "!!../node_modules/css-loader/index.js??ref--1-1!../node_modules/postcss-loader/lib/index.js??ref--1-2!../node_modules/sass-loader/lib/loader.js!./node-renderer-default.scss" in
/Users/orgpark/workspace/short-lnk/node_modules/react-sortable-tree/dist/main.js (web.browser)
  "!!../node_modules/css-loader/index.js??ref--1-1!../node_modules/postcss-loader/lib/index.js??ref--1-2!../node_modules/sass-loader/lib/loader.js!./placeholder-renderer-default.scss" in
/Users/orgpark/workspace/short-lnk/node_modules/react-sortable-tree/dist/main.js (web.browser)
  "!!../node_modules/css-loader/index.js??ref--1-1!../node_modules/postcss-loader/lib/index.js??ref--1-2!../node_modules/sass-loader/lib/loader.js!./react-sortable-tree.scss" in
/Users/orgpark/workspace/short-lnk/node_modules/react-sortable-tree/dist/main.js (web.browser)
```

Is there any work around for this issue?

**Comment by orgpark** [comment] 2018-01-04 03:45
Tried a few things but nothing really worked so far

**Comment by fritz-c** [comment] 2018-01-07 01:58
duplicate of #217 
See my comments there.

**Closed** 2018-01-07 01:58 UTC
Labels: bug, duplicate
